<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Media.Automations-c094f04d-11a2-4b97-b5c1-89c809c75f98</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Media.Data\Medias.Data.csproj" />
    <ProjectReference Include="..\Media.Server\Medias.Server.csproj" />
  </ItemGroup>
</Project>
