// <auto-generated />
using System;
using Medias.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Medias.Data.Migrations
{
    [DbContext(typeof(MediaDbContext))]
    [Migration("20260629030002_MusicBrainzRecordingIdMadeNullable")]
    partial class MusicBrainzRecordingIdMadeNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Medias.Data.Entities.Album", b =>
                {
                    b.Property<int>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverArtPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MusicBrainzReleaseGroupId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("MusicBrainzReleaseId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Studio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("CollectionId");

                    b.HasIndex("Artist");

                    b.HasIndex("MusicBrainzReleaseId")
                        .IsUnique();

                    b.HasIndex("Studio");

                    b.ToTable("Albums", (string)null);
                });

            modelBuilder.Entity("Medias.Data.Entities.AlbumTrack", b =>
                {
                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiscNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrackNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrackId");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("CollectionId", "MediaItemId")
                        .IsUnique();

                    b.HasIndex("CollectionId", "DiscNumber", "TrackNumber")
                        .IsUnique();

                    b.ToTable("AlbumTracks", (string)null);
                });

            modelBuilder.Entity("Medias.Data.Entities.Collection", b =>
                {
                    b.Property<int>("CollectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("CollectionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Collections", (string)null);
                });

            modelBuilder.Entity("Medias.Data.Entities.Library", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("LibraryType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path");

                    b.ToTable("Libraries", (string)null);
                });

            modelBuilder.Entity("Medias.Data.Entities.MediaFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Checksum");

                    b.HasIndex("FilePath");

                    b.HasIndex("MediaItemId");

                    b.ToTable("MediaFiles", (string)null);
                });

            modelBuilder.Entity("Medias.Data.Entities.MediaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("LibraryId");

                    b.HasIndex("MediaType");

                    b.HasIndex("Title");

                    b.ToTable("MediaItems", (string)null);
                });

            modelBuilder.Entity("Medias.Data.Entities.MediaItemCollection", b =>
                {
                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MediaItemId", "CollectionId");

                    b.HasIndex("CollectionId");

                    b.ToTable("MediaItemCollections", (string)null);
                });

            modelBuilder.Entity("Medias.Data.Entities.MovieDetail", b =>
                {
                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImdbId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Runtime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Studio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TmdbMovieId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MediaItemId");

                    b.HasIndex("Director");

                    b.HasIndex("Genre");

                    b.HasIndex("Studio");

                    b.ToTable("MovieDetails", (string)null);
                });

            modelBuilder.Entity("Medias.Data.Entities.MusicDetail", b =>
                {
                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverArtPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstReleased")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MusicBrainzRecordingId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<int>("Runtime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Studio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Writer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("MediaItemId");

                    b.HasIndex("Artist");

                    b.HasIndex("Genre");

                    b.HasIndex("Studio");

                    b.HasIndex("Writer");

                    b.ToTable("MusicDetails", (string)null);
                });

            modelBuilder.Entity("Medias.Data.Entities.TelevisionEpisode", b =>
                {
                    b.Property<int>("EpisodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AirDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(3, 1)
                        .HasColumnType("TEXT");

                    b.Property<int>("Runtime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TelevisionShowId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("EpisodeId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("SeasonId", "EpisodeNumber")
                        .IsUnique();

                    b.ToTable("TelevisionEpisodes", (string)null);
                });

            modelBuilder.Entity("Medias.Data.Entities.TelevisionSeason", b =>
                {
                    b.Property<int>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("SeasonId");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("MediaItemId", "SeasonNumber")
                        .IsUnique();

                    b.ToTable("TelevisionSeasons", (string)null);
                });

            modelBuilder.Entity("Medias.Data.Entities.TelevisionShowDetail", b =>
                {
                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImdbId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rating")
                        .HasPrecision(3, 1)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Studio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TmdbTvId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MediaItemId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Genre");

                    b.HasIndex("Studio");

                    b.HasIndex("TmdbTvId");

                    b.ToTable("TelevisionShowDetails", (string)null);
                });

            modelBuilder.Entity("Medias.Data.Entities.Album", b =>
                {
                    b.HasOne("Medias.Data.Entities.Collection", "Collection")
                        .WithOne("Album")
                        .HasForeignKey("Medias.Data.Entities.Album", "CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("Medias.Data.Entities.AlbumTrack", b =>
                {
                    b.HasOne("Medias.Data.Entities.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Medias.Data.Entities.MusicDetail", "MusicDetail")
                        .WithMany("AlbumTracks")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("MusicDetail");
                });

            modelBuilder.Entity("Medias.Data.Entities.MediaFile", b =>
                {
                    b.HasOne("Medias.Data.Entities.MediaItem", "MediaItem")
                        .WithMany("MediaFiles")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Medias.Data.Entities.MediaItem", b =>
                {
                    b.HasOne("Medias.Data.Entities.Library", "Library")
                        .WithMany("MediaItems")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Library");
                });

            modelBuilder.Entity("Medias.Data.Entities.MediaItemCollection", b =>
                {
                    b.HasOne("Medias.Data.Entities.Collection", "Collection")
                        .WithMany("MediaItemCollections")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Medias.Data.Entities.MediaItem", "MediaItem")
                        .WithMany("MediaItemCollections")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Medias.Data.Entities.MovieDetail", b =>
                {
                    b.HasOne("Medias.Data.Entities.MediaItem", "MediaItem")
                        .WithOne("MovieDetail")
                        .HasForeignKey("Medias.Data.Entities.MovieDetail", "MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Medias.Data.Entities.MusicDetail", b =>
                {
                    b.HasOne("Medias.Data.Entities.MediaItem", "MediaItem")
                        .WithOne("MusicDetail")
                        .HasForeignKey("Medias.Data.Entities.MusicDetail", "MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Medias.Data.Entities.TelevisionEpisode", b =>
                {
                    b.HasOne("Medias.Data.Entities.TelevisionSeason", "TelevisionSeason")
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelevisionSeason");
                });

            modelBuilder.Entity("Medias.Data.Entities.TelevisionSeason", b =>
                {
                    b.HasOne("Medias.Data.Entities.TelevisionShowDetail", "TelevisionShowDetail")
                        .WithMany("Seasons")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelevisionShowDetail");
                });

            modelBuilder.Entity("Medias.Data.Entities.TelevisionShowDetail", b =>
                {
                    b.HasOne("Medias.Data.Entities.MediaItem", "MediaItem")
                        .WithOne("TelevisionShowDetail")
                        .HasForeignKey("Medias.Data.Entities.TelevisionShowDetail", "MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Medias.Data.Entities.Album", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Medias.Data.Entities.Collection", b =>
                {
                    b.Navigation("Album");

                    b.Navigation("MediaItemCollections");
                });

            modelBuilder.Entity("Medias.Data.Entities.Library", b =>
                {
                    b.Navigation("MediaItems");
                });

            modelBuilder.Entity("Medias.Data.Entities.MediaItem", b =>
                {
                    b.Navigation("MediaFiles");

                    b.Navigation("MediaItemCollections");

                    b.Navigation("MovieDetail");

                    b.Navigation("MusicDetail");

                    b.Navigation("TelevisionShowDetail");
                });

            modelBuilder.Entity("Medias.Data.Entities.MusicDetail", b =>
                {
                    b.Navigation("AlbumTracks");
                });

            modelBuilder.Entity("Medias.Data.Entities.TelevisionSeason", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("Medias.Data.Entities.TelevisionShowDetail", b =>
                {
                    b.Navigation("Seasons");
                });
#pragma warning restore 612, 618
        }
    }
}
