using System;
using System.Collections.Generic;
using System.Text;
using Medias.Data.Entities;
using Medias.Shared.DTOs;

namespace Medias.Data.Conversions
{
    public static class LibraryConversions
    {
        public static Library ToLibrary(this LibraryDto dto)
        {
            return new Library
            {
                Id = dto.Id,
                Name = dto.Name,
                Description = dto.Description,
                Path = dto.Path,
                LibraryType = dto.LibraryType,
                CreatedDate = dto.CreatedDate,
            };
        }

        public static Library CreateDtoToLibrary(this CreateLibraryDto dto)
        {
            return new Library
            {
                Id = 0, // Id will be generated by the database
                Name = dto.Name,
                Description = dto.Description,
                Path = dto.Path,
                LibraryType = dto.LibraryType,
                CreatedDate = DateTime.UtcNow,
            };
        }

        public static Library UpdateDtoToLibrary(this UpdateLibraryDto dto, Library existingEntity)
        {
            existingEntity.Name = dto.Name;
            existingEntity.Description = dto.Description;
            existingEntity.Path = dto.Path;
            existingEntity.LibraryType = dto.LibraryType;
            existingEntity.UpdatedDate = DateTime.UtcNow;
            return existingEntity;
        }

        public static LibraryDto ToLibraryDto(this Library entity)
        {
            return new LibraryDto
            {
                Id = entity.Id,
                Name = entity.Name,
                Description = entity.Description,
                Path = entity.Path,
                LibraryType = entity.LibraryType,
                CreatedDate = entity.CreatedDate,
                UpdatedDate = entity.UpdatedDate,
            };
        }
    }
}
