using System;
using System.Collections.Generic;
using System.Text;
using Medias.Data.Entities;
using Medias.Shared.DTOs;

namespace Medias.Data.Conversions
{
    public static class MediaItemConversions
    {
        public static MediaItem ToMediaItem(this MediaItemDto dto)
        {
            return new MediaItem
            {
                Id = dto.Id,
                Title = dto.Title,
                Description = dto.Description,
                MediaType = dto.MediaType,
                CreatedDate = dto.CreatedDate,
                UpdatedDate = dto.UpdatedDate,
                LibraryId = dto.LibraryId,
                ThumbnailPath = dto.ThumbnailPath,

            };
        }

        public static MediaItem CreateDtoToMediaItem(this CreateMediaItemDto dto)
        {
            return new MediaItem
            {
                Id = 0, // Id will be generated by the database
                Title = dto.Title,
                Description = dto.Description,
                MediaType = dto.MediaType,
                CreatedDate = DateTime.UtcNow,
                UpdatedDate = DateTime.UtcNow,
                LibraryId = dto.LibraryId,
                ThumbnailPath = dto.ThumbnailPath,
            };
        }

        public static MediaItem UpdateDtoToMediaItem(this UpdateMediaItemDto dto, MediaItem existingEntity)
        {
            existingEntity.Title = dto.Title;
            existingEntity.Description = dto.Description;
            existingEntity.MediaType = dto.MediaType;
            existingEntity.UpdatedDate = DateTime.UtcNow;
            existingEntity.LibraryId = dto.LibraryId;
            existingEntity.ThumbnailPath = dto.ThumbnailPath;
            return existingEntity;
        }



        public static MediaItemDto ToMediaItemDto(this MediaItem entity)
        {
            return new MediaItemDto
            {
                Id = entity.Id,
                Title = entity.Title,
                Description = entity.Description,
                MediaType = entity.MediaType,
                CreatedDate = entity.CreatedDate,
                UpdatedDate = entity.UpdatedDate,
                LibraryId = entity.LibraryId,
                ThumbnailPath = entity.ThumbnailPath,
            };
        }

        public static MediaItemDtoFull ToMediaItemDtoFull(this MediaItem entity)
        {
            var mediaItemFull = new MediaItemDtoFull
            {
                Id = entity.Id,
                Title = entity.Title,
                Description = entity.Description,
                MediaType = entity.MediaType,
                CreatedDate = entity.CreatedDate,
                UpdatedDate = entity.UpdatedDate,
                LibraryId = entity.LibraryId,
                ThumbnailPath = entity.ThumbnailPath
                
            };
            if(entity.MovieDetail != null)
            {
                mediaItemFull.MovieDetails = entity.MovieDetail?.ToMovieDetailsDto();
            }

            if(entity.TelevisionShowDetail != null)
            {
                mediaItemFull.TelevisionShowDetails = entity.TelevisionShowDetail.ToTelevisionShowDto();
            }

            /*if(entity.MusicDetail != null)
            {
                mediaItemFull.MusicDetails = entity.MusicDetail.ToMusicDto();
            }*/

            return mediaItemFull;
        }

        public static MovieDetailsDto ToMovieDetailsDto(this MovieDetail entity)
        {
            return new MovieDetailsDto()
            {
                Runtime = entity.Runtime,
                ReleaseDate = entity.ReleaseDate,
                Director = entity.Director,
                Studio = entity.Studio,
                Genre = entity.Genre,
                Rating = entity.Rating,
            };
        }

        public static TelevisionShowDto ToTelevisionShowDto(this TelevisionShowDetail entity)
        {
            var televisionShowDto = new TelevisionShowDto();
            televisionShowDto.CreatedBy = entity.CreatedBy;
            televisionShowDto.Studio = entity.Studio;
            televisionShowDto.Genre = entity.Genre;
            televisionShowDto.Rating = entity.Rating;
            televisionShowDto.Status = entity.Status;
            televisionShowDto.TmdbTvId = entity.TmdbTvId;
            televisionShowDto.ImdbId = entity.ImdbId;
            televisionShowDto.SeasonCount = entity.SeasonCount;
            televisionShowDto.Seasons?.Clear();
            televisionShowDto.Seasons = new List<TelevisionSeasonDto>();
            if(entity.Seasons != null && entity.Seasons.Count > 0)
            {
                foreach(var season in entity.Seasons)
                {
                    var seasonDto = season.ToTelevisionSeasonDto();
                    televisionShowDto.Seasons.Add(seasonDto);
                }
            }
            return televisionShowDto;
        }

        public static TelevisionSeasonDto ToTelevisionSeasonDto(this TelevisionSeason entity)
        {
            var televisionSeason = new TelevisionSeasonDto();
            televisionSeason.SeasonId = entity.SeasonId;
            televisionSeason.TelevisionShowId = entity.MediaItemId;
            televisionSeason.SeasonNumber = entity.SeasonNumber;
            televisionSeason.Name = entity.Name;
            televisionSeason.Description = entity.Description;
            televisionSeason.EpisodeCount = entity.EpisodeCount;
            televisionSeason.Episodes?.Clear();
            televisionSeason.Episodes = new List<TelevisionEpisodeDto>();
            if(entity.Episodes != null && entity.Episodes.Count > 0)
            {
                foreach(var episode in entity.Episodes)
                {
                    var episodeDto = episode.ToTelevisionEpisodeDto();
                    televisionSeason.Episodes.Add(episodeDto);
                }
            }
            return televisionSeason;
        }

        public static TelevisionEpisodeDto ToTelevisionEpisodeDto(this TelevisionEpisode entity)
        {
            return new TelevisionEpisodeDto()
            {
                EpisodeId = entity.EpisodeId,
                EpisodeNumber = entity.EpisodeNumber,
                TelevisionShowId = entity.TelevisionShowId,
                SeasonId = entity.SeasonId,
                SeasonNumber = entity.SeasonNumber,
                Title = entity.Title,
                Description = entity.Description,
                Director = entity.Director,
                AirDate = entity.AirDate,
                Runtime = entity.Runtime,
                Rating = entity.Rating
            };
        }

       public static MusicDto ToMusicDto(this MusicDetail entity)
        {
            return new MusicDto()
            {
                Artist = entity.Artist,
                Writer = entity.Writer,
                Studio = entity.Studio,
                Genre = entity.Genre,
                FirstReleased = entity.FirstReleased,
                Rating = entity.Rating,
                CoverArtPath = entity.CoverArtPath,
                MusicBrainzRecordingId = entity.MusicBrainzRecordingId,
                RuntimeMinutes = entity.Runtime / 60,
                RuntimeSeconds = entity.Runtime % 60
            };
        }
    }
}
