using System;
using System.Collections.Generic;
using System.Text;
using Medias.Data.Entities;
using Medias.Shared.DTOs;

namespace Medias.Data.Conversions
{
    public static class MediaFileConversions
    {
        public static MediaFile ToMediaFile(this MediaFileDto dto)
        {
            return new MediaFile
            {
                Id = dto.Id,
                MediaItemId = dto.MediaItemId,
                FileName = dto.FileName,
                FilePath = dto.FilePath,
                FileSize = dto.FileSize,
                FileType = dto.FileType,
                Checksum = dto.Checksum,
                CreatedDate = dto.CreatedDate,
                UpdatedDate = dto.UpdatedDate,
                MediaItem = dto.MediaItem.ToMediaItem()
            };
        }

        public static MediaFile CreateDtoToMediaFile(this CreateMediaFileDto dto)
        {
            return new MediaFile
            {
                Id = 0, // Id will be generated by the database
                MediaItemId = dto.MediaItemId,
                FileName = dto.FileName,
                FilePath = dto.FilePath,
                FileSize = dto.FileSize,
                FileType = dto.FileType,
                Checksum = dto.Checksum,
                CreatedDate = DateTime.UtcNow,
                UpdatedDate = DateTime.UtcNow
            };
        }

        public static MediaFile UpdateDtoToMediaFile(this UpdateMediaFileDto dto, MediaFile existingEntity)
        {
            existingEntity.MediaItemId = dto.MediaItemId;
            existingEntity.FileName = dto.FileName;
            existingEntity.FilePath = dto.FilePath;
            existingEntity.FileSize = dto.FileSize;
            existingEntity.FileType = dto.FileType;
            existingEntity.Checksum = dto.Checksum;
            existingEntity.UpdatedDate = DateTime.UtcNow;
            return existingEntity;
        }

        public static MediaFileDto ToMediaFileDto(this MediaFile entity)
        {
            return new MediaFileDto
            {
                Id = entity.Id,
                MediaItemId = entity.MediaItemId,
                FileName = entity.FileName,
                FilePath = entity.FilePath,
                FileSize = entity.FileSize,
                FileType = entity.FileType,
                Checksum = entity.Checksum,
                CreatedDate = entity.CreatedDate,
                UpdatedDate = entity.UpdatedDate,
                MediaItem = entity.MediaItem.ToMediaItemDto()
            };
        }
    }
}