using System;
using System.Collections.Generic;
using System.Text;
using Medias.Data.Entities;
using Medias.Shared.DTOs;

namespace Medias.Data.Conversions
{
    public static class MediaItemConversions
    {
        public static MediaItem ToMediaItem(this MediaItemDto dto)
        {
            return new MediaItem
            {
                Id = dto.Id,
                Title = dto.Title,
                Description = dto.Description,
                MediaType = dto.MediaType,
                CreatedDate = dto.CreatedDate,
                UpdatedDate = dto.UpdatedDate,
                LibraryId = dto.LibraryId,
                ThumbnailPath = dto.ThumbnailPath,

            };
        }

        public static MediaItem CreateDtoToMediaItem(this CreateMediaItemDto dto)
        {
            return new MediaItem
            {
                Id = 0, // Id will be generated by the database
                Title = dto.Title,
                Description = dto.Description,
                MediaType = dto.MediaType,
                CreatedDate = DateTime.UtcNow,
                UpdatedDate = DateTime.UtcNow,
                LibraryId = dto.LibraryId,
                ThumbnailPath = dto.ThumbnailPath,
            };
        }

        public static MediaItem UpdateDtoToMediaItem(this UpdateMediaItemDto dto, MediaItem existingEntity)
        {
            existingEntity.Title = dto.Title;
            existingEntity.Description = dto.Description;
            existingEntity.MediaType = dto.MediaType;
            existingEntity.UpdatedDate = DateTime.UtcNow;
            existingEntity.LibraryId = dto.LibraryId;
            existingEntity.ThumbnailPath = dto.ThumbnailPath;
            return existingEntity;
        }

        public static MediaItemDto ToMediaItemDto(this MediaItem entity)
        {
            return new MediaItemDto
            {
                Id = entity.Id,
                Title = entity.Title,
                Description = entity.Description,
                MediaType = entity.MediaType,
                CreatedDate = entity.CreatedDate,
                UpdatedDate = entity.UpdatedDate,
                LibraryId = entity.LibraryId,
                ThumbnailPath = entity.ThumbnailPath,
            };
        }

        public static MediaItemDtoFull ToMediaItemDtoFull(this MediaItem entity)
        {
            var mediaItemFull = new MediaItemDtoFull
            {
                Id = entity.Id,
                Title = entity.Title,
                Description = entity.Description,
                MediaType = entity.MediaType,
                CreatedDate = entity.CreatedDate,
                UpdatedDate = entity.UpdatedDate,
                LibraryId = entity.LibraryId,
                ThumbnailPath = entity.ThumbnailPath
                
            };
            if(entity.MovieDetail != null)
            {
                mediaItemFull.MovieDetails = entity.MovieDetail?.ToMovieDetailsDto();
            }

            return mediaItemFull;
        }

        public static MovieDetailsDto ToMovieDetailsDto(this MovieDetail entity)
        {
            return new MovieDetailsDto()
            {
                Runtime = entity.Runtime,
                ReleaseDate = entity.ReleaseDate,
                Director = entity.Director,
                Studio = entity.Studio,
                Genre = entity.Genre,
                Rating = entity.Rating,
            };
        }
    }
}
